import Bayiliklerimiz from "../components/Urunler/Bayiliklerimiz";
import Hizmetlerimiz from "../components/Urunler/Hizmetlerimiz";
import UrunlerHeader from "../components/Urunler/UrunlerHeader";
import Urunlerimiz from "../components/Urunler/Urunlerimiz";
import Sektorler from "../components/Urunler/Sektorler";
import Head from "next/head";
import React from "react";
import Dokumantasyon from "../components/Dokumantasyon/Dokumantasyon";

const dokumantasyon = () => {
  return (
    <>
      <Head>
        <title>Pengona Software</title>
        <meta name="description" content="Generated by Pengona" />
      </Head>
      <main className=" w-full mb-16 flex flex-col items-center justify-center ">
        <Dokumantasyon/>        
      </main>
    </>
  );
};

export default dokumantasyon;
