// import GetContact from "@/components/Iletisim/GetContact";
import Haritalar from "../components/Iletisim/Haritalar";
import Head from "next/head";
import React from "react";

const iletisim = () => {
  return (
    <>
      <Head>
        <title>Pengona Software İletişim Bilgileri</title>
        <meta name="description" content="Generated by Pengona" />
      </Head>
      <main className=" w-full mb-16 flex flex-col items-center justify-center ">
        {/* <GetContact/> */}
        <div className="w-full flex flex-col justify-center items-center lg:px-24 md:px-12 px-4 py-12 text-[#001653]">
          <h5 className="w-full text-center lg:text-3xl md:text-3xl text-3xl mb-4 font-bold ">
            Pengona Yazılım ve Mühendislik İletişim Bilgileri
          </h5>
          <div className="w-full lg:grid lg:grid-cols-3 flex flex-col gap-4">
            <p className="w-full text-center lg:text-xl md:text-lg text-base mb-8">
              <span className="font-semibold">Pengona Yazılım Adresi:</span>
              <br></br> Kosova Mahallesi Güneş Sokak No:1G <br></br>
              <span className="font-semibold"> Selçuklu KONYA - TÜRKİYE</span>
            </p>
            <p className="w-full text-center lg:text-xl md:text-lg text-base mb-8">
              <span className="font-semibold">Pengona Yazılım Email:</span>
              <br></br> info@pengona.com <br></br>
            </p>
            <p className="w-full text-center lg:text-xl md:text-lg text-base mb-8">
              <span className="font-semibold">Pengona Yazılım Telefon:</span>
              <br></br> +90 543 352 42 56<br></br>
              <span className="font-semibold mt-4">Teknik Destek :</span>
              <br></br> +90 507 863 29 25<br></br>
            </p>
          </div>
        </div>
        {/* <Haritalar /> */}
      </main>
    </>
  );
};

export default iletisim;
